[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
  SECRETS_SCAN_OMIT_KEYS = "EMAIL_HOST,EMAIL_PASS,EMAIL_PORT,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL,STRAVA_CLIENT_SECRET,SUPABASE_SERVICE_ROLE_KEY,WEATHERAPI_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"
